# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Sasha & Team"

# URL
baseurl:            "/dance2016/"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "About"
    href:           "/dance2016/about"
  - name:           "Contact"
    href:           "/dance2016/contact"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
